### PR TITLE
back fix (probably)

### PR DESCRIPTION
**Pull request by sudo-nautilus**
There's possibility of breaking things,
But can easily revet

### CODE REVIEW

**Comment by sudo-nautilus** [comment]
It **may** work

**Comment by IzumiCypherX** [comment]
@sudo-nautilus I already reverted like 18 changes cuz it just started to break the bot 😂

**Comment by IzumiCypherX** [comment]
@sudo-nautilus It broke The Commands Button Instead👍

**Comment by sudo-nautilus** [comment]
@IzumiCypherX so, can I revet this?

**Pull request merged**
