### PR TITLE
Emilia UwU

### PR DESCRIPTION
**Pull request by sudo-nautilus**
This basically un-kangifies Saitama,
You may test it first

### CODE REVIEW

**Comment by sudo-nautilus** [comment]
Changed `SaitamaRobot` --> `EmiliaAnimeBot`
                 `Saitama` --> `Emilia`

**Comment by IzumiCypherX** [comment]
@sudo-nautilus Thanks For the Great Work Mate.
here take a cookie

**Comment by sudo-nautilus** [comment]
VS code is incredible, you know :trollface:

**Comment by sudo-nautilus** [comment]
Wait a sec, will that thing even work?

https://user-images.githubusercontent.com/78522210/132455803-3b52e0ec-f667-4b41-bd2a-07a975098b42.mov

**Comment by IzumiCypherX** [comment]
@sudo-nautilus haha true

**Comment by sudo-nautilus** [comment]
It should work,
Are you responding through Telegram?

**Comment by IzumiCypherX** [comment]
> It should work,
> Are you responding through Telegram?

i did, now on git

**Comment by sudo-nautilus** [comment]
> > It should work,
> > Are you responding through Telegram?
> 
> i did, now on git

Oh ok lol

**Pull request merged**
