### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by IzuMeow**

### CODE REVIEW

**Comment by IzumiCypherX** [comment]
@IzuMeow Oh demn

**Comment by sudo-nautilus** [comment]
@IzumiCypherX Noice

**Comment by sudo-nautilus** [comment]
Is @IzuMeow your alt? 

@IzumiCypherX

**Comment by IzumiCypherX** [comment]
@sudo-nautilus Yes

**Comment by sudo-nautilus** [comment]
> @sudo-nautilus Yes

I see

**Pull request merged**
