### PR TITLE
Deepsource changes

### PR DESCRIPTION
**Pull request by sudo-nautilus**
Yeah,
Rebase merge this time

### CODE REVIEW

**Comment by sudo-nautilus** [comment]
@IzumiCypherX you may remove deepsource for this repo, I guess. Because it's quite awful to see a `failed` (that red X) symbol/icon/marking on each pushes and prs

**Comment by ArshCypherZ** [comment]
@sudo-nautilus i see

**Comment by IzumiCypherX** [comment]
@sudo-nautilus Yea it looks kind of weird

**Comment by sudo-nautilus** [comment]
True 
rember

**Pull request merged**
